# Generated by Django 5.1 on 2024-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('password_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
